version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - 9876:9876
    environment:
      PORT: 9876
