import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps(context){
  const res = await fetch('http://localhost:9876/package',{
    method: "GET",
    headers: {
          // update with your user-agent
          "User-Agent":
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36", 
          Accept: "application/json; charset=UTF-8",
        },
  })
  const message = await res.json();
  return { 
    props: {message}
    }  ;
}

export default function Home({message}) {

  function handleClick() {
    alert('clicked!');
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.center}>
          <h1> Welcome to 461 Part 2! </h1>
          <p>By: Ben Brown</p>
        </div>
        <div>
          <a href="http://localhost:9876/package" target="_blank">
            <button> Sample API button </button>
          </a>
        </div>
        <div>
          <button onClick={handleClick}>
            hello
          </button>
        </div>
        <div>message: {message.message}</div>
      </main>
    </>
  )
}