import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import FileInput from './zipUpload'

const inter = Inter({ subsets: ['latin'] })

/*export async function getStaticProps(context){
  const res = await fetch('http://localhost:8000/package')
const message = await res.json();

  return { 
    props: {message}
    }  ;
}*/

export default function Home({message}) {

  function handleClick() {
    alert('clicked!');
  }

  const [url, setURL] = useState('');
  /*const [packageName, setName] = useState('');
  const [packageVersion, setVersion] = useState('');*/
  const [postID, setPostID] = useState();
  const [zipData, setZipData] = useState('');
  const [postName, setPostName] = useState('');
  const [postVersion, setPostVersion] = useState('');
  const [rows, setRows] = useState([]);
  

  const addRow = () => {
    const newRow = { ID: postID, Name: postName, Version: postVersion };
    setRows([...rows, newRow]);
    setPostID('');
    setPostName('');
    setPostVersion('');
  };

  const handleFileSubmit = (base64Data) => {
    //setFileData(base64Data)
    setZipData(base64Data)
    //e.preventDefault();
    //sendPostRequest(b64String);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    //const dataStruct = { packageName, packageVersion, url}; //content};
    const dataStruct = { url };
    
    fetch(`${process.env.NEXT_PUBLIC_BACKEND_API}`, {
      method: 'POST',
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(dataStruct)
    }).then(response => {
        response.json()
      })
      .then(data => console.log(data))
      .catch(error => console.error(error));
    //const addRow = { ID: response.}

  }

  /*const sendPostRequest = (b64String) => {
      fetch(`${process.env.NEXT_PUBLIC_BACKEND_API}`, {
          method: 'POST',
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ Content: b64String})
      })
  };//response?*/

  /*function FileInput() {
    const [selectedZip, setSelectedZip] = useState(null)

  }*/
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.center}>
          <h1> Welcome to 461 Part 2! </h1>
          <p>By: Ben Brown</p>
        </div>
  {/*      <div>
          <a href="http://localhost:8000/package" target="_blank">
            <button> Sample API button </button>
          </a>
  </div>*/}
        <div>
          <button onClick={handleClick}>
            hello
          </button>
        </div>
        {/*<div>message: {message.message}</div>*/}
        <h3> Create Package From URL</h3>
        <form onSubmit={handleSubmit}>
          <label>Enter URL</label>
          <input
            type="text" 
            required
            value={url}
            onChange={(e) => setURL(e.target.value)}
            />
          <button>Submit</button>
        </form>
        <center>
          <FileInput handleSubmit={handleFileSubmit}/>
          {zipData && (
            <div>
              <h2>File data:</h2>
              <p>{zipData}</p>
            </div>
          )}
        </center>

        <div>
          <h1>Packages</h1>
          <table>
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th> 
                <th>Version</th>
              </tr>
            </thead>
            <tbody>

            </tbody>
          </table>
        </div>
      </main>
    </>
  )
}