steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project461p/temp_p2:9dd2963d92064524f03047cbabd65190d805f7c9:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project461p/temp_p2:9dd2963d92064524f03047cbabd65190d805f7c9:$SHORT_SHA']
