name: CI/CD
on:
  push:
    branches: [joel]
  pull_request:
    branches: [joel]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: install flake
      run: pip install flake8
    - name: run flake
      run: |
        flake8 .
